type: files
files:
  - nvidia/sway-nvidia.sh: /usr/bin/sway-nvidia
  - nvidia/sway-nvidia.desktop: /usr/share/wayland-sessions/sway-nvidia.desktop
  - nvidia/wlroots-env-nvidia.sh: /usr/share/wlroots-nvidia/wlroots-env-nvidia.sh
  - nvidia/sddm-compositor-sway: /usr/libexec/sddm-compositor-sway
