modules:

  - type: files
    files:
      - usr: /usr # copy static configurations
                  # configuration you wish to end up in /etc/ on the booted system should be
                  # added into /usr/etc/ as that is the proper "distro" config directory on ostree
                  # read more in the files module's README

  - from-file: packages.yml
  - from-file: bling.yml
  - from-file: yafti.yml

  - type: script
    scripts:
      # fetches local RPMs (Mullvad VPN)
      - fetch-rpms.sh
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
