- type: rpm-ostree
  repos: 
    # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
  install:
    - python3-pip # required for yafti
    - libadwaita # required for yafti
    - sway
    - xdg-desktop-portal-wlr
    - waybar
    - xorg-x11-server-Xwayland
    - xdg-user-dirs
    # android
    - android-tools
    - android-file-transfer
    # common utils
    - swaybg
    - swayidle
    - swaylock
    - power-profiles-daemon
    - polkit-gnome
    - libseat
    - network-manager-applet
    - system-config-printer
    - firewall-config
    - blueman
    - thunar
    - thunar-archive-plugin
    - imv
    - kvantum
    - exa
    - gnome-disk-utility
    - mako
    - xarchiver
    - pavucontrol
    # text editor
    - lite-xl
    # qt shiz
    - qt5ct
    - qt6ct
    - qt6-qtwayland
    - qt5-qtwayland
    - qt5-qtgraphicaleffects
    - qt5-qtquickcontrols2
    - qt5-qtsvg
    # launchers
    - fuzzel
    # terminals
    - foot
    # screenshotting
    - grimshot
    - wdisplays
    - gnome-keyring
    # fonts
    - overpass-fonts
    - overpass-mono-fonts
    # config deps
    - light
    - fish
    - wtype
    - papirus-icon-theme
    # audio
    - pipewire
    - wireplumber
    - pipewire-alsa
    - pipewire-jack-audio-connection-kit
    - pipewire-pulseaudio
    # git askpass
    - ksshaskpass
  remove:
    - firefox # default firefox removed in favor of flatpak
    - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
    - toolbox
    - sway-config-fedora
    - dunst
    - rofi-wayland
    - jack-audio-connection-kit
  optfix:
    - Mullvad VPN
