# image will be published to ghcr.io/<user>/<name>
name: usway-rewrite
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main
image-version: 38 # latest is also supported if you want new updates ASAP

# list of modules that will be executed in order
# you can include multiple of the same module
modules:
  - type: rpm-ostree
    repos: 
      # - https://copr.fedorainfracloud.org/coprs/atim/starship/repo/fedora-%OS_VERSION%/atim-starship-fedora-%OS_VERSION%.repo
    install:
      - python3-pip # required for yafti
      - libadwaita # required for yafti
      - sway
      - xdg-desktop-portal-wlr
      - waybar
      - xorg-x11-server-Xwayland
      - xdg-user-dirs
      # android
      - android-tools
      - android-file-transfer
      # common utils
      - swaybg
      - swayidle
      - swaylock
      - power-profiles-daemon
      - polkit-gnome
      - libseat
      - network-manager-applet
      - system-config-printer
      - firewall-config
      - blueman
      - thunar
      - thunar-archive-plugin
      - imv
      - kvantum
      - exa
      - gnome-disk-utility
      - mako
      - xarchiver
      - pavucontrol
      # text editor
      - lite-xl
      # qt shiz
      - qt5ct
      - qt6ct
      - qt6-qtwayland
      - qt5-qtwayland
      - qt5-qtgraphicaleffects
      - qt5-qtquickcontrols2
      - qt5-qtsvg
      # launchers
      - fuzzel
      # terminals
      - foot
      # screenshotting
      - grimshot
      - wdisplays
      - gnome-keyring
      # fonts
      - overpass-fonts
      - overpass-mono-fonts
      # config deps
      - light
      - fish
      - wtype
      - papirus-icon-theme
      # audio
      - pipewire
      - wireplumber
      - pipewire-alsa
      - pipewire-jack-audio-connection-kit
      - pipewire-pulseaudio
      # git askpass
      - ksshaskpass
    remove:
      - firefox # default firefox removed in favor of flatpak
      - firefox-langpacks # langpacks needs to also be removed to prevent dependency problems
      - toolbox
      - sway-config-fedora
      - dunst
      - rofi-wayland
      - jack-audio-connection-kit
    optfix:
      - Mullvad VPN

  - type: bling # configure what to pull in from ublue-os/bling
    install:
      - fonts # selection of common good free fonts
      - justfiles # add "!include /usr/share/ublue-os/just/bling.just"
                  # in your custom.just (added by default) or local justfile
      - nix-installer # shell shortcuts for determinate system's nix installers
      - ublue-os-wallpapers
      - ublue-update # https://github.com/ublue-os/ublue-update
      # - dconf-update-service # a service unit that updates the dconf db on boot
      # - devpod # https://devpod.sh/ as an rpm


  - type: yafti # if included, https://github.com/ublue-os/yafti will be installed and set up
    custom-flatpaks: # this section is optional
      - org.freedesktop.Platform.ffmpeg-full/x86_64/22.08
      - io.mpv.Mpv
      - org.kde.kwalletmanager5
      - org.gtk.Gtk3theme.adw-gtk3-dark

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - fetch-rpms.sh

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh 
