# image will be published to ghcr.io/<user>/<name>
name: usway-nvidia
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-nvidia
image-version: 38 # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - sway-nvidia.sh: /usr/bin/sway-nvidia
      - sway-nvidia.desktop: /usr/share/wayland-sessions/sway-nvidia.desktop
      - wlroots_env_nvidia.sh: /usr/share/wlroots-nvidia/wlroots-env-nvidia.sh
  - from-file: common.yml
  # nvidia specific files
