# image will be published to ghcr.io/<user>/<name>
name: usway-nvidia
# description will be included in the image's metadata
description: custom sericea image for nvidia desktop

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-nvidia
image-version: 39 # latest is also supported if you want new updates ASAP

# list of modules, executed in order
# you can include multiple instances of the same module
modules:
  - from-file: module_config/desktop.yml
  - from-file: module_config/nvidia.yml
  - from-file: common.yml
