# image will be published to ghcr.io/<user>/<name>
name: usway-rewrite
# description will be included in the image's metadata
description: custom sericea image

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main
image-version: 38 # latest is also supported if you want new updates ASAP

# list of modules that will be executed in order
# you can include multiple of the same module
modules:
  - from-file: packages.yml
  - from-file: bling.yml
  - from-file: yafti.yml

- type: script
  scripts:
    # fetches local RPMs (Mullvad VPN)
    - fetch-rpms.sh

- type: script
  scripts:
    # this sets up the proper policy & signing files for signed images to work
    - signing.sh
