# image will be published to ghcr.io/<user>/<name>
name: usway
# description will be included in the image's metadata
description: A starting point for further customization of uBlue images. Make your own! https://ublue.it/making-your-own/

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/sericea-main
image-version: 38 # latest is also supported if you want new updates ASAP

# list of modules that will be executed in order

# you can include multiple of the same module

modules:
  - type: files
    files:
      - usr: /usr

  # Copy static configurations and component files.
  # Warning: If you want to place anything in "/etc" of the final image, you MUST
  # place them in "./usr/etc" in your repo, so that they're written to "/usr/etc"
  # on the final system. That is the proper directory for "system" configuration
  # templates on immutable Fedora distros, whereas the normal "/etc" is ONLY meant
  # for manual overrides and editing by the machine's admin AFTER installation!
  # See issue #28 (https://github.com/ublue-os/startingpoint/issues/28).

  - from-file: packages.yml
  - from-file: bling.yml
  - from-file: yafti.yml

  - type: script
    scripts:
      # fetches local RPMs (Mullvad VPN)
      - fetch-rpms.sh

  - type: script
    scripts:
      # this sets up the proper policy & signing files for signed images to work
      - signing.sh
